use myStore;

CREATE TABLE users(

id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
f_name VARCHAR(30) NOT NULL;
l_name VARCHAR(30) NOT NULL;
email VARCHAR(50) NOT NULL UNIQUE;
username VARCHAR(30) NOT NULL UNIQUE;
pwd LONGTEXT NOT NULL UNIQUE;

);
